services:

  app:
    build: .
    image: workshop-organizer
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/workshopsdb"
      SPRING_DATASOURCE_USERNAME: workshops_user
      SPRING_DATASOURCE_PASSWORD: oc2024
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: workshops_user
      POSTGRES_PASSWORD: oc2024
      POSTGRES_DB: workshopsdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/00001_0.0.0_init_create.sql:/docker-entrypoint-initdb.d/00001_init_create.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U workshops_user -d workshopsdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data: